#ifndef PELLATIO_COMMON_GLOBAL_H
#define PELLATIO_COMMON_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PELLATIO_COMMON_LIBRARY)
#  define PELLATIO_COMMONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PELLATIO_COMMONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PELLATIO_COMMON_GLOBAL_H
