#ifndef PELLATIO_SERVER_GLOBAL_H
#define PELLATIO_SERVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PELLATIO_SERVER_LIBRARY)
#  define PELLATIO_SERVERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PELLATIO_SERVERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PELLATIO_SERVER_GLOBAL_H
